# Generated by Django 4.1.7 on 2023-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menuitem_parrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='nesting_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Nesting level'),
        ),
    ]
