# Generated by Django 4.1.7 on 2023-04-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menuitem_parrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_chosen',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Item has been chosen'),
        ),
    ]
