# Generated by Django 4.1.7 on 2023-02-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menuitem_nesting_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['parrent__id']},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='main.menuitem', verbose_name='Parrent item'),
        ),
    ]
