# Generated by Django 4.1.7 on 2023-05-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menuitem_parrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='nesting_level',
        ),
    ]
